### ISSUE TITLE
links to old repository?

### ISSUE THREAD

**Issue by evanwill** [walshbr/textanalysiscoursebook#14]
I noticed links in the readme.md point to the Issues and repo at https://github.com/walshbr/introduction-to-text-analysis rather than this repository. Is this version the most up-to-date? Should the links be updated?

Great book / project, thank you.

**Comment by walshbr** [comment]
Ah thanks for the catch! The two repositories are effectively identical, minus a few line edits that I might have made while correcting them. This repository here is the version of record, so I'll update those links accordingly. The old repository that you link to there is the repository that consists of the materials as they were originally crafted and published on GitBook. But I was running into issues with their interface, so I converted things to the Jekyll repository that you see here so as to maintain it myself.

Glad the project is useful!
